<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK93nQog\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK93nQog/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerK93nQog.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerK93nQog\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerK93nQog\App_KernelDevDebugContainer([
    'container.build_hash' => 'K93nQog',
    'container.build_id' => '3e9bb1bc',
    'container.build_time' => 1673348809,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerK93nQog');
